name: Update POM Version on Commit

on:
  push:
    branches:
      - main # Ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para fazer git push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Busca todo o histórico para calcular a versão corretamente

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ação para incrementar a versão no POM baseada em Conventional Commits
      - name: Bump Version
        id: bump
        uses: richardInnocent/semantic-versioning-maven@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Opcional: define a branch para push se diferente da original
          # ref: ${{ github.head_ref }}

      - name: Commit and Push Changes
        if: steps.bump.outputs.bumped == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new-version }}"
          git push
